### ISSUE TITLE
Bien, mais ?

### ISSUE THREAD

**Issue by SnorkY** [CelestinV/SR03-Trombinoscope#1]
Bonjour, 
Je cherche un script trombinoscope clé en main.

Le tiens semble plutôt excellent, mais comment ajouter des images / infos etc ?

Merci à toi pour ton aide.

**Comment by CelestinV** [comment]
Bonjour,

Toutes les informations / images sont gérées par des webservices auxquels je fais appel afin de bien faire la distinction entre la partie affichage pure (front-end) et recherche des informations(back-end).

Ce script fait appel à plusieurs webservices: 
- Un premier (noté "https://webapplis.utc.fr/Trombi_ws/mytrombi/result?nom=XXX&prenom=YYY") renvoie un fichier JSON contenant toutes les informations à propos de la personne/des personnes en fonction de la recherche par nom/prénom.
- Un second (noté "https://webapplis.utc.fr/Trombi_ws/mytrombi/structpere") permet d'extraire via un fichier JSON les différentes structues pères. Tu l'auras certainement compris, il y a un autre webservices pour les sous structure et enfin un pour effectuer sa recherche.
- Un dernier permet à partir des information de la personne recherchée d'avoir son image.

Si tu veux vraiment effectuer la totalité de ton trombinoscope à partir de 0 alors mon script ne pourra pas le faire. Mais si tu possèdes déjà des webservices permettant de te donner ces informations sous format JSON (ou autre format tel que XML et tu peux ensuite adapter le code) alors tu pourras l'adapter en fonctions des différentes informations que tu souhaites et de leur noms dans ton fichier.

Sinon tu peux toujours l'utiliser et créer toi même des webservices créant les fichiers JSON, exercice pas très ardu et qui peut être sympa à faire :) ! 

L'avantage de l'utilisation de ces webservices et qu'ils te permettent de gérer ton code de recherche séparément de ton code d'affichage et par exemple pour la recherche par structure, d'être totalement indépendant et de ne pas ta soucier de la structure de ta compagnie/groupe pour lequel tu veux faire ton trombinoscope une fois créer.

En espérant avoir répondu à ton interrogation.
Célestin
